animations {
    enabled = yes
    bezier = niriSpring, 0.23, 1, 0.32, 1
    bezier = niriFast, 0.15, 0, 0.1, 1
    bezier = niriSmooth, 0.5, 0.5, 0.75, 1
    animation = global, 1, 10, default
    animation = border, 1, 5.39, niriSpring
    animation = windows, 1, 4.79, niriSpring
    animation = windowsIn, 1, 4.1, niriSpring, popin 87%
    animation = windowsOut, 1, 1.49, niriFast, popin 87%
    animation = fadeIn, 1, 1.73, niriSmooth
    animation = fadeOut, 1, 1.46, niriSmooth
    animation = fade, 1, 3.03, niriFast
    animation = layers, 1, 3.81, niriSpring
    animation = layersIn, 1, 4, niriSpring, fade
    animation = layersOut, 1, 1.5, niriFast, fade
    animation = fadeLayersIn, 1, 1.79, niriSmooth
    animation = fadeLayersOut, 1, 1.39, niriSmooth
    animation = workspaces, 1, 1.94, niriSmooth, fade
    animation = workspacesIn, 1, 1.21, niriSmooth, fade
    animation = workspacesOut, 1, 1.94, niriSmooth, fade
}
