# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0def4"

# Title color for boxes
theme[title]="#c4a7e7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f6c177"

# Background color of selected item in processes box
theme[selected_bg]="#c4a7e7"

# Foreground color of selected item in processes box
theme[selected_fg]="#191724"

# Color of inactive/disabled text
theme[inactive_fg]="#e0def4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f6c177"

# Cpu box outline color
theme[cpu_box]="#908caa"

# Memory/disks box outline color
theme[mem_box]="#908caa"

# Net up/down box outline color
theme[net_box]="#908caa"

# Processes box outline color
theme[proc_box]="#908caa"

# Box divider line and small boxes line color
theme[div_line]="#1f1d2e"

# Temperature graph colors
theme[temp_start]="#f6c177"
theme[temp_mid]="#c4a7e7"
theme[temp_end]="#eb6f92"

# CPU graph colors
theme[cpu_start]="#f6c177"
theme[cpu_mid]="#c4a7e7"
theme[cpu_end]="#eb6f92"

# Mem/Disk free meter
theme[free_start]="#f6c177"
theme[free_mid]=""
theme[free_end]="#1f1d2e"

# Mem/Disk cached meter
theme[cached_start]="#f6c177"
theme[cached_mid]=""
theme[cached_end]="#1f1d2e"

# Mem/Disk available meter
theme[available_start]="#c4a7e7"
theme[available_mid]=""
theme[available_end]="#26233a"

# Mem/Disk used meter
theme[used_start]="#eb6f92"
theme[used_mid]=""
theme[used_end]="#8c1d18"

# Download graph colors
theme[download_start]="#f6c177"
theme[download_mid]="#c4a7e7"
theme[download_end]="#f6c177"

# Upload graph colors
theme[upload_start]="#f6c177"
theme[upload_mid]="#c4a7e7"
theme[upload_end]="#f6c177"
