# btop TTY config - fluorescent green theme
# TTY environment only

#* Name of a btop++/bpytop/bashtop formatted ".theme" file
color_theme = "green-tty"

#* If the theme set background should be shown
theme_background = true

#* Sets if 24-bit truecolor should be used
truecolor = false

#* Will force 16-color mode and TTY theme
force_tty = true

#* Graph symbols for TTY mode
tty_mode = true

#* Update time in milliseconds
update_ms = 2000

#* Processes sorting option
proc_sorting = "memory"

#* Reverse sorting order
proc_reversed = false

#* Show process tree
proc_tree = true

#* Show memory as graph
mem_graphs = true

#* Show swap in memory box
show_swap = true

#* Show disk I/O
disk_io = true

#* Show network activity
net_io = true

#* Show battery
show_battery = true
