exec-once = dms run
exec-once = killcry
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = systemctl --user set-environment XDG_SESSION_CLASS=user
exec-once = fcitx5
exec-once = ~/.config/niri/scripts/screenshot-sound.sh
exec-once = xhost +si:localuser:root
exec-once = dsearch serve
exec-once = systemctl --user start linuxqq-clipsync
