-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(c4a7e7)",
			inactive_border = "rgb(908caa)",
		},
	},
	group = {
		col = {
			border_active = "rgb(c4a7e7)",
			border_inactive = "rgb(908caa)",
			border_locked_active = "rgb(eb6f92)",
			border_locked_inactive = "rgb(908caa)",
		},
		groupbar = {
			col = {
				active = "rgb(c4a7e7)",
				inactive = "rgb(908caa)",
				locked_active = "rgb(eb6f92)",
				locked_inactive = "rgb(908caa)",
			},
		},
	},
})
