# tactical/starship.toml

format = """
┌───$username$hostname$directory $time $git_branch$git_status $c$cpp$dart$deno$elixir$golang$haskell$java$julia$kotlin$lua$nodejs$perl$php$python$rlang$ruby$rust$scala$swift$zig
└─$character"""

continuation_prompt = ". "

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "@$hostname"

[directory]
truncation_length = 5
truncate_to_repo = true

[time]
disabled = false
time_format = "%H:%M"
format = "at $time "

[git_branch]

[git_status]

[c]
disabled = false
symbol = "C:"
format = "$symbol$version "

[cpp]
disabled = false
symbol = "C++:"
format = "$symbol$version "

[dart]
symbol = "Dart:"
format = "$symbol$version "

[deno]
symbol = "Deno:"
format = "$symbol$version "

[elixir]
symbol = "Elixir:"
format = "$symbol$version "

[golang]
symbol = "Go:"
format = "$symbol$version "

[haskell]
symbol = "Haskell:"
format = "$symbol$version "

[java]
symbol = "Java:"
format = "$symbol$version "

[julia]
symbol = "Julia:"
format = "$symbol$version "

[kotlin]
symbol = "Kotlin:"
format = "$symbol$version "

[lua]
symbol = "Lua:"
format = "$symbol$version "

[nodejs]
symbol = "Node:"
format = "$symbol$version "

[perl]
symbol = "Perl:"
format = "$symbol$version "

[php]
symbol = "PHP:"
format = "$symbol$version "

[python]
symbol = "Python:"
format = "$symbol$version "

[rlang]
symbol = "R:"
format = "$symbol$version "

[ruby]
symbol = "Ruby:"
format = "$symbol$version "

[rust]
symbol = "Rust:"
format = "$symbol$version "

[scala]
symbol = "Scala:"
format = "$symbol$version "

[swift]
symbol = "Swift:"
format = "$symbol$version "

[zig]
symbol = "Zig:"
format = "$symbol$version "

[character]
success_symbol = ">"
error_symbol = ">"
format = "$symbol "
