# tactical/starship.toml
# Dynamic config based on DMS theme (milkTheme)

format = """
┌──\\[$username\\](bold fg:#d97706)─\\[$hostname\\](bold fg:#3b82f6)─\\[$directory\\](bold fg:#e6d4d8)─($time)(bold fg:#e6d4d8) $git_branch$git_status $c$cpp$dart$deno$elixir$golang$haskell$java$julia$kotlin$lua$nodejs$perl$php$python$rlang$ruby$rust$scala$swift$zig
└─$character"""

add_newline = true

[username]
style_user = "bold fg:#d97706"
style_root = "bold fg:#ff0000"
show_always = true
format = "$user"

[hostname]
style = "bold fg:#3b82f6"
ssh_only = false
format = "@$hostname"

[directory]
style = "bold fg:#e6d4d8"
truncation_length = 5
truncate_to_repo = true
format = "$path "

[directory.substitutions]
"Documents" = "󰤙 "
"Downloads" = "󰆤 "
"Music" = "󰟚 "
"Pictures" = "󰎵 "
"Videos" = "󰢈 "
"Developer" = "󰣋 "
"Desktop" = "󰹨 "
"Public" = "󰟢 "
"Templates" = "󰱀 "
".config" = "󰱿 "

[time]
disabled = false
time_format = "%H:%M"
style = "bold fg:#e6d4d8"
format = "at ($time)($style) "

[git_branch]
style = "bold fg:#ac3232"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold fg:#e6d4d8"
format = "[$all_status$ahead_behind]($style) "

[c]
symbol = "C"
style = "bold fg:#A8B9CC"
format = "[$symbol$version]($style) "

[cpp]
symbol = "C++"
style = "bold fg:#00599C"
format = "[$symbol$version]($style) "

[dart]
symbol = "Dt"
style = "bold fg:#0175C2"
format = "[$symbol$version]($style) "

[deno]
symbol = "Dn"
style = "bold fg:#010101"
format = "[$symbol$version]($style) "

[elixir]
symbol = "Ex"
style = "bold fg:#6E4A7E"
format = "[$symbol$version]($style) "

[golang]
symbol = "Go"
style = "bold fg:#00ADD8"
format = "[$symbol$version]($style) "

[haskell]
symbol = "Hs"
style = "bold fg:#5e5086"
format = "[$symbol$version]($style) "

[java]
symbol = "Jv"
style = "bold fg:#ED8B00"
format = "[$symbol$version]($style) "

[julia]
symbol = "Jl"
style = "bold fg:#9558B2"
format = "[$symbol$version]($style) "

[kotlin]
symbol = "Kt"
style = "bold fg:#7F52FF"
format = "[$symbol$version]($style) "

[lua]
symbol = "Lu"
style = "bold fg:#000080"
format = "[$symbol$version]($style) "

[nodejs]
symbol = "Js"
style = "bold fg:#339933"
format = "[$symbol$version]($style) "

[perl]
symbol = "Pl"
style = "bold fg:#39457E"
format = "[$symbol$version]($style) "

[php]
symbol = "Ph"
style = "bold fg:#777BB4"
format = "[$symbol$version]($style) "

[python]
symbol = "Py"
style = "bold fg:#FFD43B"
format = "[$symbol$version]($style) "

[rlang]
symbol = "R"
style = "bold fg:#276DC3"
format = "[$symbol$version]($style) "

[ruby]
symbol = "Rb"
style = "bold fg:#CC342D"
format = "[$symbol$version]($style) "

[rust]
symbol = "Rs"
style = "bold fg:#D34516"
format = "[$symbol$version]($style) "

[scala]
symbol = "Sc"
style = "bold fg:#DC322F"
format = "[$symbol$version]($style) "

[swift]
symbol = "Sw"
style = "bold fg:#FA7343"
format = "[$symbol$version]($style) "

[zig]
symbol = "Zg"
style = "bold fg:#F7A41D"
format = "[$symbol$version]($style) "


[character]
success_symbol = "[❯](bold fg:#339933)"
error_symbol = "[❯](bold fg:#ff0000)"
vimcmd_symbol = "[❮](bold fg:#d97706)"
format = "$symbol "
