# Vertical candidate list
Vertical Candidate List=True
# Use mouse wheel to page
WheelForPaging=True
# Font
Font="Sans Serif 11"
# Menu font
MenuFont="Sans Serif 10"
# Tray font
TrayFont="Sans Serif 10"
# Tray outline color
TrayOutlineColor=#000000
# Tray text color
TrayTextColor=#ffffff
# Prefer text icon
PreferTextIcon=False
# Show layout name in icon
ShowLayoutNameInIcon=True
# Use input method language to display text
UseInputMethodLanguageToDisplayText=True
